from fastapi import FastAPI, HTTPException, Query, Depends, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Literal, Optional
from datetime import datetime, timezone

class GPU(BaseModel):
    id: int = Field(gt=0)
    brand: Literal["NVIDIA", "AMD", "Intel"]
    manufacturer: Literal[
        "NVIDIA", "AMD", "Intel", "ASUS", "MSI", "Gigabyte", "Zotac", "PNY",
        "Palit", "Colorful", "Gainward", "Inno3D", "EVGA", "PowerColor",
        "Sapphire", "XFX", "ASRock"
    ]
    model: str = Field(min_length=1)
    series: str = Field(min_length=1)
    architecture: str = Field(min_length=1)
    vram: str = Field(min_length=1)
    memory_type: Literal["DDR3", "GDDR5", "GDDR5X", "GDDR6", "GDDR6X", "GDDR7"]
    cuda_cores: int = Field(ge=0)
    core_count: int = Field(ge=0)
    core_type: Literal["CUDA Cores", "Stream Processors", "Xe Cores"]
    memory_bus: str = Field(min_length=1)
    memory_bandwidth_gbps: float = Field(
        gt=0, description="Memory bandwidth in GB/s (gigabytes per second)."
    )
    power: str = Field(min_length=1)
    base_clock: str = Field(min_length=1)
    boost_clock: str = Field(min_length=1)
    recommended_psu: str = Field(min_length=1)
    process_node_nm: int = Field(gt=0)
    pcie_interface: Literal[
        "PCIe 2.0 x8", "PCIe 2.0 x16", "PCIe 3.0 x4", "PCIe 3.0 x16",
        "PCIe 4.0 x8", "PCIe 4.0 x16", "PCIe 5.0 x8", "PCIe 5.0 x16"
    ]
    launch_price_usd: Optional[float] = Field(..., ge=0)
    release_date: str = Field(min_length=1)
    description: str = Field(min_length=1)
    

API_KEY = "apinilance"

def verify_api_key(x_api_key: str = Header(None)):
    if x_api_key != API_KEY:
        raise HTTPException(
            status_code=401,
            detail="Invalid or missing API key"
        )
    return x_api_key

app = FastAPI(
    title="Simple NVIDIA GPU API",
    description="A beginner-friendly REST API containing NVIDIA GPU information.",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

# GPU DATA
gpus = [
    {
        "id": 1,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 5090",
        "series": "GeForce RTX 50 Series",
        "architecture": "Blackwell",
        "vram": "32GB GDDR7",
        "memory_type": "GDDR7",
        "cuda_cores": 21760,
        "core_count": 21760,
        "core_type": "CUDA Cores",
        "memory_bus": "512-bit",
        "memory_bandwidth_gbps": 1792.0,
        "power": "575W",
        "base_clock": "2.01 GHz",
        "boost_clock": "2.41 GHz",
        "recommended_psu": "1000W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 5.0 x16",
        "launch_price_usd": 1999.0,
        "release_date": "January 30, 2025",
        "description": "NVIDIA's flagship GeForce graphics card.",
        "memory_bandwidth": "1792 GB/s",
        "tensor_cores": 680,
        "rt_cores": 170,
        "launch_price": "$1999",
    },
    {
        "id": 2,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 5080",
        "series": "GeForce RTX 50 Series",
        "architecture": "Blackwell",
        "vram": "16GB GDDR7",
        "memory_type": "GDDR7",
        "cuda_cores": 10752,
        "core_count": 10752,
        "core_type": "CUDA Cores",
        "memory_bus": "256-bit",
        "memory_bandwidth_gbps": 960.0,
        "power": "360W",
        "base_clock": "2.30 GHz",
        "boost_clock": "2.62 GHz",
        "recommended_psu": "850W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 5.0 x16",
        "launch_price_usd": 999.0,
        "release_date": "January 30, 2025",
        "description": "A high-end Blackwell GPU designed for gaming and AI workloads.",
    },
    {
        "id": 3,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 5070 Ti",
        "series": "GeForce RTX 50 Series",
        "architecture": "Blackwell",
        "vram": "16GB GDDR7",
        "memory_type": "GDDR7",
        "cuda_cores": 8960,
        "core_count": 8960,
        "core_type": "CUDA Cores",
        "memory_bus": "256-bit",
        "memory_bandwidth_gbps": 896.0,
        "power": "300W",
        "base_clock": "2.30 GHz",
        "boost_clock": "2.45 GHz",
        "recommended_psu": "750W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 5.0 x16",
        "launch_price_usd": 749.0,
        "release_date": "February 20, 2025",
        "description": "A high-performance GPU for gaming and creative workloads.",
    },
    {
        "id": 4,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 4090",
        "series": "GeForce RTX 40 Series",
        "architecture": "Ada Lovelace",
        "vram": "24GB GDDR6X",
        "memory_type": "GDDR6X",
        "cuda_cores": 16384,
        "core_count": 16384,
        "core_type": "CUDA Cores",
        "memory_bus": "384-bit",
        "memory_bandwidth_gbps": 1008.0,
        "power": "450W",
        "base_clock": "2.23 GHz",
        "boost_clock": "2.52 GHz",
        "recommended_psu": "850W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 4.0 x16",
        "launch_price_usd": 1599.0,
        "release_date": "October 12, 2022",
        "description": "A previous-generation flagship GeForce GPU.",
    },
    {
        "id": 5,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 4080 SUPER",
        "series": "GeForce RTX 40 Series",
        "architecture": "Ada Lovelace",
        "vram": "16GB GDDR6X",
        "memory_type": "GDDR6X",
        "cuda_cores": 10240,
        "core_count": 10240,
        "core_type": "CUDA Cores",
        "memory_bus": "256-bit",
        "memory_bandwidth_gbps": 736.0,
        "power": "320W",
        "base_clock": "2.29 GHz",
        "boost_clock": "2.55 GHz",
        "recommended_psu": "750W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 4.0 x16",
        "launch_price_usd": 999.0,
        "release_date": "January 31, 2024",
        "description": "A high-end Ada Lovelace GPU.",
    },
    {
        "id": 6,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 5070",
        "series": "GeForce RTX 50 Series",
        "architecture": "Blackwell",
        "vram": "12GB GDDR7",
        "memory_type": "GDDR7",
        "cuda_cores": 6144,
        "core_count": 6144,
        "core_type": "CUDA Cores",
        "memory_bus": "192-bit",
        "memory_bandwidth_gbps": 672.0,
        "power": "250W",
        "base_clock": "2.33 GHz",
        "boost_clock": "2.51 GHz",
        "recommended_psu": "650W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 5.0 x16",
        "launch_price_usd": 549.0,
        "release_date": "March 5, 2025",
        "description": "A Blackwell GPU aimed at high-performance 1440p gaming.",
    },
    {
        "id": 7,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 5060 Ti",
        "series": "GeForce RTX 50 Series",
        "architecture": "Blackwell",
        "vram": "16GB GDDR7",
        "memory_type": "GDDR7",
        "cuda_cores": 4608,
        "core_count": 4608,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 448.0,
        "power": "180W",
        "base_clock": "2.41 GHz",
        "boost_clock": "2.57 GHz",
        "recommended_psu": "600W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 5.0 x8",
        "launch_price_usd": 429.0,
        "release_date": "April 16, 2025",
        "description": "A mid-range Blackwell GPU available with high-capacity GDDR7 memory.",
    },
    {
        "id": 8,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 5060",
        "series": "GeForce RTX 50 Series",
        "architecture": "Blackwell",
        "vram": "8GB GDDR7",
        "memory_type": "GDDR7",
        "cuda_cores": 3840,
        "core_count": 3840,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 448.0,
        "power": "145W",
        "base_clock": "2.28 GHz",
        "boost_clock": "2.50 GHz",
        "recommended_psu": "550W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 5.0 x8",
        "launch_price_usd": 299.0,
        "release_date": "May 19, 2025",
        "description": "A mainstream Blackwell GPU designed for modern 1080p gaming.",
    },
    {
        "id": 9,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 4070 Ti SUPER",
        "series": "GeForce RTX 40 Series",
        "architecture": "Ada Lovelace",
        "vram": "16GB GDDR6X",
        "memory_type": "GDDR6X",
        "cuda_cores": 8448,
        "core_count": 8448,
        "core_type": "CUDA Cores",
        "memory_bus": "256-bit",
        "memory_bandwidth_gbps": 672.0,
        "power": "285W",
        "base_clock": "2.34 GHz",
        "boost_clock": "2.61 GHz",
        "recommended_psu": "700W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 4.0 x16",
        "launch_price_usd": 799.0,
        "release_date": "January 24, 2024",
        "description": "A powerful Ada Lovelace GPU suitable for 1440p and 4K gaming.",
    },
    {
        "id": 10,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 4070 SUPER",
        "series": "GeForce RTX 40 Series",
        "architecture": "Ada Lovelace",
        "vram": "12GB GDDR6X",
        "memory_type": "GDDR6X",
        "cuda_cores": 7168,
        "core_count": 7168,
        "core_type": "CUDA Cores",
        "memory_bus": "192-bit",
        "memory_bandwidth_gbps": 504.0,
        "power": "220W",
        "base_clock": "1.98 GHz",
        "boost_clock": "2.48 GHz",
        "recommended_psu": "650W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 4.0 x16",
        "launch_price_usd": 599.0,
        "release_date": "January 17, 2024",
        "description": "An upgraded RTX 4070-class GPU focused on high-refresh-rate 1440p gaming.",
    },
    {
        "id": 11,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 4070",
        "series": "GeForce RTX 40 Series",
        "architecture": "Ada Lovelace",
        "vram": "12GB GDDR6X",
        "memory_type": "GDDR6X",
        "cuda_cores": 5888,
        "core_count": 5888,
        "core_type": "CUDA Cores",
        "memory_bus": "192-bit",
        "memory_bandwidth_gbps": 504.0,
        "power": "200W",
        "base_clock": "1.92 GHz",
        "boost_clock": "2.48 GHz",
        "recommended_psu": "650W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 4.0 x16",
        "launch_price_usd": 599.0,
        "release_date": "April 13, 2023",
        "description": "An efficient Ada Lovelace GPU designed primarily for 1440p gaming.",
    },
    {
        "id": 12,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 4060 Ti",
        "series": "GeForce RTX 40 Series",
        "architecture": "Ada Lovelace",
        "vram": "16GB GDDR6",
        "memory_type": "GDDR6",
        "cuda_cores": 4352,
        "core_count": 4352,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 288.0,
        "power": "165W",
        "base_clock": "2.31 GHz",
        "boost_clock": "2.54 GHz",
        "recommended_psu": "550W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 4.0 x8",
        "launch_price_usd": 499.0,
        "release_date": "July 18, 2023",
        "description": "A mid-range Ada Lovelace GPU aimed at high-performance 1080p gaming.",
    },
    {
        "id": 13,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 4060",
        "series": "GeForce RTX 40 Series",
        "architecture": "Ada Lovelace",
        "vram": "8GB GDDR6",
        "memory_type": "GDDR6",
        "cuda_cores": 3072,
        "core_count": 3072,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 272.0,
        "power": "115W",
        "base_clock": "1.83 GHz",
        "boost_clock": "2.46 GHz",
        "recommended_psu": "550W",
        "process_node_nm": 4,
        "pcie_interface": "PCIe 4.0 x8",
        "launch_price_usd": 299.0,
        "release_date": "June 29, 2023",
        "description": "A mainstream Ada Lovelace graphics card designed for efficient 1080p gaming.",
    },
    {
        "id": 14,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 3090 Ti",
        "series": "GeForce RTX 30 Series",
        "architecture": "Ampere",
        "vram": "24GB GDDR6X",
        "memory_type": "GDDR6X",
        "cuda_cores": 10752,
        "core_count": 10752,
        "core_type": "CUDA Cores",
        "memory_bus": "384-bit",
        "memory_bandwidth_gbps": 1008.0,
        "power": "450W",
        "base_clock": "1.56 GHz",
        "boost_clock": "1.86 GHz",
        "recommended_psu": "850W",
        "process_node_nm": 8,
        "pcie_interface": "PCIe 4.0 x16",
        "launch_price_usd": 1999.0,
        "release_date": "March 29, 2022",
        "description": "The flagship RTX 30-series GPU with 24GB of GDDR6X memory.",
    },
    {
        "id": 15,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 3090",
        "series": "GeForce RTX 30 Series",
        "architecture": "Ampere",
        "vram": "24GB GDDR6X",
        "memory_type": "GDDR6X",
        "cuda_cores": 10496,
        "core_count": 10496,
        "core_type": "CUDA Cores",
        "memory_bus": "384-bit",
        "memory_bandwidth_gbps": 936.0,
        "power": "350W",
        "base_clock": "1.40 GHz",
        "boost_clock": "1.70 GHz",
        "recommended_psu": "750W",
        "process_node_nm": 8,
        "pcie_interface": "PCIe 4.0 x16",
        "launch_price_usd": 1499.0,
        "release_date": "September 24, 2020",
        "description": "A high-end Ampere GPU built for gaming, rendering, and demanding creative workloads.",
    },
    {
        "id": 16,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 3080 Ti",
        "series": "GeForce RTX 30 Series",
        "architecture": "Ampere",
        "vram": "12GB GDDR6X",
        "memory_type": "GDDR6X",
        "cuda_cores": 10240,
        "core_count": 10240,
        "core_type": "CUDA Cores",
        "memory_bus": "384-bit",
        "memory_bandwidth_gbps": 912.0,
        "power": "350W",
        "base_clock": "1.37 GHz",
        "boost_clock": "1.67 GHz",
        "recommended_psu": "750W",
        "process_node_nm": 8,
        "pcie_interface": "PCIe 4.0 x16",
        "launch_price_usd": 1199.0,
        "release_date": "June 3, 2021",
        "description": "A high-end Ampere GPU designed for demanding 4K gaming.",
    },
    {
        "id": 17,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce RTX 3080",
        "series": "GeForce RTX 30 Series",
        "architecture": "Ampere",
        "vram": "10GB GDDR6X",
        "memory_type": "GDDR6X",
        "cuda_cores": 8704,
        "core_count": 8704,
        "core_type": "CUDA Cores",
        "memory_bus": "320-bit",
        "memory_bandwidth_gbps": 760.0,
        "power": "320W",
        "base_clock": "1.44 GHz",
        "boost_clock": "1.71 GHz",
        "recommended_psu": "750W",
        "process_node_nm": 8,
        "pcie_interface": "PCIe 4.0 x16",
        "launch_price_usd": 699.0,
        "release_date": "September 17, 2020",
        "description": "A popular Ampere graphics card designed for high-end gaming.",
    },
    {
        "id": 18,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1660 Ti",
        "series": "GeForce GTX 16 Series",
        "architecture": "Turing",
        "vram": "6GB GDDR6",
        "memory_type": "GDDR6",
        "cuda_cores": 1536,
        "core_count": 1536,
        "core_type": "CUDA Cores",
        "memory_bus": "192-bit",
        "memory_bandwidth_gbps": 288.0,
        "power": "120W",
        "base_clock": "1.50 GHz",
        "boost_clock": "1.77 GHz",
        "recommended_psu": "450W",
        "process_node_nm": 12,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 279.0,
        "release_date": "February 22, 2019",
        "description": "A Turing-based GTX graphics card designed for strong 1080p gaming.",
    },
    {
        "id": 19,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1660 SUPER",
        "series": "GeForce GTX 16 Series",
        "architecture": "Turing",
        "vram": "6GB GDDR6",
        "memory_type": "GDDR6",
        "cuda_cores": 1408,
        "core_count": 1408,
        "core_type": "CUDA Cores",
        "memory_bus": "192-bit",
        "memory_bandwidth_gbps": 336.0,
        "power": "125W",
        "base_clock": "1.53 GHz",
        "boost_clock": "1.785 GHz",
        "recommended_psu": "450W",
        "process_node_nm": 12,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 229.0,
        "release_date": "October 29, 2019",
        "description": "A popular GTX card offering solid performance for 1080p gaming.",
    },
    {
        "id": 20,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1650 SUPER",
        "series": "GeForce GTX 16 Series",
        "architecture": "Turing",
        "vram": "4GB GDDR6",
        "memory_type": "GDDR6",
        "cuda_cores": 1280,
        "core_count": 1280,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 192.0,
        "power": "100W",
        "base_clock": "1.53 GHz",
        "boost_clock": "1.725 GHz",
        "recommended_psu": "350W",
        "process_node_nm": 12,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 159.0,
        "release_date": "November 22, 2019",
        "description": "An entry-level Turing GPU designed for affordable 1080p gaming.",
    },
    {
        "id": 21,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1650",
        "series": "GeForce GTX 16 Series",
        "architecture": "Turing",
        "vram": "4GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 896,
        "core_count": 896,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 128.0,
        "power": "75W",
        "base_clock": "1.485 GHz",
        "boost_clock": "1.665 GHz",
        "recommended_psu": "300W",
        "process_node_nm": 12,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 149.0,
        "release_date": "April 23, 2019",
        "description": "An entry-level Turing GPU designed for efficient 1080p gaming.",
    },
    {
        "id": 22,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1080 Ti",
        "series": "GeForce GTX 10 Series",
        "architecture": "Pascal",
        "vram": "11GB GDDR5X",
        "memory_type": "GDDR5X",
        "cuda_cores": 3584,
        "core_count": 3584,
        "core_type": "CUDA Cores",
        "memory_bus": "352-bit",
        "memory_bandwidth_gbps": 484.0,
        "power": "250W",
        "base_clock": "1.480 GHz",
        "boost_clock": "1.582 GHz",
        "recommended_psu": "600W",
        "process_node_nm": 16,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 699.0,
        "release_date": "March 10, 2017",
        "description": "The flagship GTX 10-series gaming GPU based on NVIDIA's Pascal architecture.",
    },
    {
        "id": 23,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1080",
        "series": "GeForce GTX 10 Series",
        "architecture": "Pascal",
        "vram": "8GB GDDR5X",
        "memory_type": "GDDR5X",
        "cuda_cores": 2560,
        "core_count": 2560,
        "core_type": "CUDA Cores",
        "memory_bus": "256-bit",
        "memory_bandwidth_gbps": 320.0,
        "power": "180W",
        "base_clock": "1.607 GHz",
        "boost_clock": "1.733 GHz",
        "recommended_psu": "500W",
        "process_node_nm": 16,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 599.0,
        "release_date": "May 27, 2016",
        "description": "A high-end Pascal GPU designed for high-performance 1440p and 4K gaming.",
    },
    {
        "id": 24,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1070 Ti",
        "series": "GeForce GTX 10 Series",
        "architecture": "Pascal",
        "vram": "8GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 2432,
        "core_count": 2432,
        "core_type": "CUDA Cores",
        "memory_bus": "256-bit",
        "memory_bandwidth_gbps": 256.0,
        "power": "180W",
        "base_clock": "1.607 GHz",
        "boost_clock": "1.683 GHz",
        "recommended_psu": "500W",
        "process_node_nm": 16,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 449.0,
        "release_date": "November 2, 2017",
        "description": "A high-performance Pascal GPU positioned between the GTX 1070 and GTX 1080.",
    },
    {
        "id": 25,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1070",
        "series": "GeForce GTX 10 Series",
        "architecture": "Pascal",
        "vram": "8GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 1920,
        "core_count": 1920,
        "core_type": "CUDA Cores",
        "memory_bus": "256-bit",
        "memory_bandwidth_gbps": 256.0,
        "power": "150W",
        "base_clock": "1.506 GHz",
        "boost_clock": "1.683 GHz",
        "recommended_psu": "500W",
        "process_node_nm": 16,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 379.0,
        "release_date": "June 10, 2016",
        "description": "A Pascal GPU designed for strong 1440p gaming performance.",
    },
    {
        "id": 26,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1060",
        "series": "GeForce GTX 10 Series",
        "architecture": "Pascal",
        "vram": "6GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 1280,
        "core_count": 1280,
        "core_type": "CUDA Cores",
        "memory_bus": "192-bit",
        "memory_bandwidth_gbps": 192.0,
        "power": "120W",
        "base_clock": "1.506 GHz",
        "boost_clock": "1.708 GHz",
        "recommended_psu": "400W",
        "process_node_nm": 16,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 249.0,
        "release_date": "July 19, 2016",
        "description": "A popular mid-range Pascal GPU designed for high-quality 1080p gaming.",
    },
    {
        "id": 27,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1050 Ti",
        "series": "GeForce GTX 10 Series",
        "architecture": "Pascal",
        "vram": "4GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 768,
        "core_count": 768,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 112.0,
        "power": "75W",
        "base_clock": "1.290 GHz",
        "boost_clock": "1.392 GHz",
        "recommended_psu": "300W",
        "process_node_nm": 14,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 139.0,
        "release_date": "October 25, 2016",
        "description": "An efficient entry-level Pascal GPU designed for affordable 1080p gaming.",
    },
    {
        "id": 28,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 1050",
        "series": "GeForce GTX 10 Series",
        "architecture": "Pascal",
        "vram": "2GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 640,
        "core_count": 640,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 112.0,
        "power": "75W",
        "base_clock": "1.354 GHz",
        "boost_clock": "1.455 GHz",
        "recommended_psu": "300W",
        "process_node_nm": 14,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 109.0,
        "release_date": "October 25, 2016",
        "description": "An entry-level Pascal graphics card designed for low-power 1080p gaming.",
    },
    {
        "id": 29,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 980 Ti",
        "series": "GeForce GTX 900 Series",
        "architecture": "Maxwell",
        "vram": "6GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 2816,
        "core_count": 2816,
        "core_type": "CUDA Cores",
        "memory_bus": "384-bit",
        "memory_bandwidth_gbps": 336.0,
        "power": "250W",
        "base_clock": "1.000 GHz",
        "boost_clock": "1.075 GHz",
        "recommended_psu": "600W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 649.0,
        "release_date": "June 2, 2015",
        "description": "A flagship-class Maxwell GPU designed for enthusiast gaming.",
    },
    {
        "id": 30,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 980",
        "series": "GeForce GTX 900 Series",
        "architecture": "Maxwell",
        "vram": "4GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 2048,
        "core_count": 2048,
        "core_type": "CUDA Cores",
        "memory_bus": "256-bit",
        "memory_bandwidth_gbps": 224.0,
        "power": "165W",
        "base_clock": "1.126 GHz",
        "boost_clock": "1.216 GHz",
        "recommended_psu": "500W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 549.0,
        "release_date": "September 18, 2014",
        "description": "A high-end Maxwell graphics card designed for enthusiast gaming.",
    },
    {
        "id": 31,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 970",
        "series": "GeForce GTX 900 Series",
        "architecture": "Maxwell",
        "vram": "4GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 1664,
        "core_count": 1664,
        "core_type": "CUDA Cores",
        "memory_bus": "256-bit",
        "memory_bandwidth_gbps": 224.0,
        "power": "145W",
        "base_clock": "1.050 GHz",
        "boost_clock": "1.178 GHz",
        "recommended_psu": "500W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 329.0,
        "release_date": "September 18, 2014",
        "description": "A popular Maxwell GPU that offered strong gaming performance and power efficiency.",
    },
    {
        "id": 32,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 960",
        "series": "GeForce GTX 900 Series",
        "architecture": "Maxwell",
        "vram": "2GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 1024,
        "core_count": 1024,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 112.0,
        "power": "120W",
        "base_clock": "1.127 GHz",
        "boost_clock": "1.178 GHz",
        "recommended_psu": "400W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 199.0,
        "release_date": "January 22, 2015",
        "description": "A mainstream Maxwell GPU designed primarily for 1080p gaming.",
    },
    {
        "id": 33,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 780 Ti",
        "series": "GeForce GTX 700 Series",
        "architecture": "Kepler",
        "vram": "3GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 2880,
        "core_count": 2880,
        "core_type": "CUDA Cores",
        "memory_bus": "384-bit",
        "memory_bandwidth_gbps": 336.0,
        "power": "250W",
        "base_clock": "0.875 GHz",
        "boost_clock": "0.928 GHz",
        "recommended_psu": "600W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 699.0,
        "release_date": "November 7, 2013",
        "description": "The flagship GTX 700-series Kepler GPU designed for enthusiast gaming.",
    },
    {
        "id": 34,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GTX 780",
        "series": "GeForce GTX 700 Series",
        "architecture": "Kepler",
        "vram": "3GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 2304,
        "core_count": 2304,
        "core_type": "CUDA Cores",
        "memory_bus": "384-bit",
        "memory_bandwidth_gbps": 288.4,
        "power": "250W",
        "base_clock": "0.863 GHz",
        "boost_clock": "0.900 GHz",
        "recommended_psu": "600W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 649.0,
        "release_date": "May 23, 2013",
        "description": "A high-end Kepler graphics card designed for enthusiast gaming.",
    },
    {
        "id": 35,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 1030",
        "series": "GeForce GT 10 Series",
        "architecture": "Pascal",
        "vram": "2GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 384,
        "core_count": 384,
        "core_type": "CUDA Cores",
        "memory_bus": "64-bit",
        "memory_bandwidth_gbps": 48.0,
        "power": "30W",
        "base_clock": "1.227 GHz",
        "boost_clock": "1.468 GHz",
        "recommended_psu": "300W",
        "process_node_nm": 14,
        "pcie_interface": "PCIe 3.0 x4",
        "launch_price_usd": 69.99,
        "release_date": "May 17, 2017",
        "description": "An entry-level Pascal GPU designed for multimedia, esports, and light gaming.",
    },
    {
        "id": 36,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 1010",
        "series": "GeForce GT 10 Series",
        "architecture": "Pascal",
        "vram": "2GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 256,
        "core_count": 256,
        "core_type": "CUDA Cores",
        "memory_bus": "64-bit",
        "memory_bandwidth_gbps": 40.1,
        "power": "30W",
        "base_clock": "1.228 GHz",
        "boost_clock": "1.468 GHz",
        "recommended_psu": "200W",
        "process_node_nm": 14,
        "pcie_interface": "PCIe 3.0 x4",
        # Public launch MSRP could not be verified; see the module notes.
        "launch_price_usd": None,
        "release_date": "January 13, 2021",
        "description": "A low-power OEM Pascal GPU intended for basic graphics and multimedia workloads.",
    },
    {
        "id": 37,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 740",
        "series": "GeForce GT 700 Series",
        "architecture": "Kepler",
        "vram": "1GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 384,
        "core_count": 384,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 80.0,
        "power": "64W",
        "base_clock": "0.993 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "400W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 89.0,
        "release_date": "May 29, 2014",
        "description": "An entry-level Kepler GPU offering improved multimedia and light gaming performance.",
    },
    {
        "id": 38,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 730",
        "series": "GeForce GT 700 Series",
        "architecture": "Kepler",
        "vram": "1GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 384,
        "core_count": 384,
        "core_type": "CUDA Cores",
        "memory_bus": "64-bit",
        "memory_bandwidth_gbps": 40.0,
        "power": "38W",
        "base_clock": "0.902 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "300W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 2.0 x8",
        "launch_price_usd": 69.0,
        "release_date": "June 18, 2014",
        "description": "A low-power Kepler graphics card designed for multimedia, productivity, and light gaming.",
    },
    {
        "id": 39,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 720",
        "series": "GeForce GT 700 Series",
        "architecture": "Kepler",
        "vram": "1GB DDR3",
        "memory_type": "DDR3",
        "cuda_cores": 192,
        "core_count": 192,
        "core_type": "CUDA Cores",
        "memory_bus": "64-bit",
        "memory_bandwidth_gbps": 12.8,
        "power": "19W",
        "base_clock": "0.797 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "300W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 2.0 x8",
        "launch_price_usd": 49.0,
        "release_date": "September 29, 2014",
        "description": "A low-power Kepler GPU intended for basic desktop graphics and multimedia.",
    },
    {
        "id": 40,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 710",
        "series": "GeForce GT 700 Series",
        "architecture": "Kepler",
        "vram": "2GB DDR3",
        "memory_type": "DDR3",
        "cuda_cores": 192,
        "core_count": 192,
        "core_type": "CUDA Cores",
        "memory_bus": "64-bit",
        "memory_bandwidth_gbps": 14.4,
        "power": "19W",
        "base_clock": "0.954 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "300W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 2.0 x8",
        "launch_price_usd": 39.99,
        "release_date": "January 26, 2016",
        "description": "An ultra-low-power Kepler GPU designed for basic display output and multimedia workloads.",
    },
    {
        "id": 41,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 640",
        "series": "GeForce GT 600 Series",
        "architecture": "Kepler",
        "vram": "2GB DDR3",
        "memory_type": "DDR3",
        "cuda_cores": 384,
        "core_count": 384,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 28.5,
        "power": "65W",
        "base_clock": "0.900 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "350W",
        "process_node_nm": 28,
        "pcie_interface": "PCIe 3.0 x16",
        "launch_price_usd": 99.0,
        "release_date": "June 5, 2012",
        "description": "A Kepler-based mainstream GPU designed for multimedia and entry-level gaming.",
    },
    {
        "id": 42,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 630",
        "series": "GeForce GT 600 Series",
        "architecture": "Fermi",
        "vram": "1GB GDDR5",
        "memory_type": "GDDR5",
        "cuda_cores": 96,
        "core_count": 96,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 51.2,
        "power": "65W",
        "base_clock": "0.810 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "300W",
        "process_node_nm": 40,
        "pcie_interface": "PCIe 2.0 x16",
        "launch_price_usd": 79.0,
        "release_date": "May 15, 2012",
        "description": "An entry-level Fermi graphics card designed for multimedia and light gaming workloads.",
    },
    {
        "id": 43,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 620",
        "series": "GeForce GT 600 Series",
        "architecture": "Fermi",
        "vram": "1GB DDR3",
        "memory_type": "DDR3",
        "cuda_cores": 96,
        "core_count": 96,
        "core_type": "CUDA Cores",
        "memory_bus": "64-bit",
        "memory_bandwidth_gbps": 14.4,
        "power": "49W",
        "base_clock": "0.700 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "300W",
        "process_node_nm": 40,
        "pcie_interface": "PCIe 2.0 x16",
        "launch_price_usd": 39.99,
        "release_date": "May 15, 2012",
        "description": "A budget Fermi GPU intended for general desktop graphics and multimedia use.",
    },
    {
        "id": 44,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 610",
        "series": "GeForce GT 600 Series",
        "architecture": "Fermi",
        "vram": "1GB DDR3",
        "memory_type": "DDR3",
        "cuda_cores": 48,
        "core_count": 48,
        "core_type": "CUDA Cores",
        "memory_bus": "64-bit",
        "memory_bandwidth_gbps": 14.4,
        "power": "29W",
        "base_clock": "0.810 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "300W",
        "process_node_nm": 40,
        "pcie_interface": "PCIe 2.0 x16",
        "launch_price_usd": 39.99,
        "release_date": "April 2, 2012",
        "description": "A low-power Fermi graphics card designed for basic desktop and multimedia applications.",
    },
    {
        "id": 45,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 520",
        "series": "GeForce GT 500 Series",
        "architecture": "Fermi",
        "vram": "1GB DDR3",
        "memory_type": "DDR3",
        "cuda_cores": 48,
        "core_count": 48,
        "core_type": "CUDA Cores",
        "memory_bus": "64-bit",
        "memory_bandwidth_gbps": 14.4,
        "power": "29W",
        "base_clock": "0.810 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "300W",
        "process_node_nm": 40,
        "pcie_interface": "PCIe 2.0 x16",
        "launch_price_usd": 59.0,
        "release_date": "April 12, 2011",
        "description": "An entry-level Fermi GPU designed primarily for HD video, multimedia, and basic graphics workloads.",
    },
    {
        "id": 46,
        "brand": "NVIDIA",
        "manufacturer": "NVIDIA",
        "model": "GeForce GT 430",
        "series": "GeForce GT 400 Series",
        "architecture": "Fermi",
        "vram": "1GB DDR3",
        "memory_type": "DDR3",
        "cuda_cores": 96,
        "core_count": 96,
        "core_type": "CUDA Cores",
        "memory_bus": "128-bit",
        "memory_bandwidth_gbps": 28.8,
        "power": "49W",
        "base_clock": "0.700 GHz",
        "boost_clock": "Not supported",
        "recommended_psu": "300W",
        "process_node_nm": 40,
        "pcie_interface": "PCIe 2.0 x16",
        "launch_price_usd": 79.0,
        "release_date": "October 11, 2010",
        "description": "An entry-level Fermi GPU designed for HD multimedia and basic gaming workloads.",
    },
]

# ON-BOOT PYDANTIC VALIDATION
validated_gpus = [GPU(**gpu).model_dump() for gpu in gpus]
gpus = validated_gpus

# HOME
@app.get("/")
def home():
    return {
        "message": "Welcome to the NVIDIA GPU API!",
        "endpoints": [
            "/gpus",
            "/gpus/{id}",
            "/gpus/search"
        ]
    }

# HEALTH CHECK
@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "service": "Simple NVIDIA GPU API",
        "timestamp": datetime.now(timezone.utc).isoformat()
    }

# GET ALL GPUS
@app.get("/gpus", dependencies=[Depends(verify_api_key)])
def get_gpus():
    return {
        "count": len(gpus),
        "gpus": gpus
    }

# EXPANDED GPU SEARCH
@app.get("/gpus/search", dependencies=[Depends(verify_api_key)])
def search_gpus(
    q: str = Query(..., min_length=1)
):
    q = q.lower().strip()

    results = []

    for gpu in gpus:
        searchable_text = " ".join([
            str(gpu["id"]),
            gpu["brand"],
            gpu["model"],
            gpu["architecture"],
            gpu["vram"],
            str(gpu["cuda_cores"]),
            gpu["memory_bus"],
            gpu["power"],
            gpu["base_clock"],
            gpu["boost_clock"],
            gpu["recommended_psu"],
            gpu["release_date"],
            gpu["description"]
        ]).lower()

        if q in searchable_text:
            results.append(gpu)

    return {
        "query": q,
        "count": len(results),
        "results": results
    }
    
# GET ONE GPU
@app.get("/gpus/{gpu_id}", dependencies=[Depends(verify_api_key)])
def get_gpu(gpu_id: int):

    for gpu in gpus:
        if gpu["id"] == gpu_id:
            return gpu

    raise HTTPException(
        status_code=404,
        detail="GPU not found."
    )


